name: pokemon_apps
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flex_color_scheme: 7.3.1
  easy_splash_screen: 1.0.4
  google_fonts: 6.1.0
  font_awesome_flutter: 10.6.0
  shared_preferences: 2.2.2
  fluttertoast: 8.2.2
  getwidget: 4.0.0
  url_launcher: 6.1.14
  easy_refresh: 3.3.2+1
  card_loading: 0.3.0
  permission_handler: 11.0.1
  just_audio: 0.9.35
  dio: 5.3.3
  google_sign_in: 6.1.5
  firebase_core: 2.19.0
  firebase_auth: 4.11.1
  flutter_easyloading: 3.0.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/audios/
  uses-material-design: true

